name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: netlify
    steps:
      - uses: actions/checkout@v2

      - name: Publish to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deployed website at v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true