name: Testing

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: netlify
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '11.10.0'

      - name: Install dependencies
        run: "npm i"

      - name: Test
        id: "test"
        run: "npm run test"

      - name: Generate coverage
        id: "coverage"
        if: steps.test.outcome == 'success'
        run: "npm run coverage"

      - name: Publish to coveralls.io
        if: steps.coverage.outcome == 'success'
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}